name: Build Godot Project

on:
  push:
    branches:
      - main
      - MG-AutomatedBuilds
env:
  GAME_NAME: WizardBubble
jobs:
  Godot:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [Windows, macOS, Web, Linux]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: ${{ env.GAME_NAME }}
          preset: ${{ matrix.platform }}
          debugMode: "true"
          projectDir: "./ggj2025"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ env.GAME_NAME }} - ${{ matrix.platform }}
          path: ggj2025/builds

      # - name: create release
      #   uses: ncipollo/release-action@v1.14.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     generateReleaseNotes: true
      #     tag: ${{ github.ref_name }}
      #     artifacts: ${{ steps.export.outputs.archive_directory }}/*