name: Build Godot Project

on:
  # all branches
  push:
    branches:
      - main
      - MG-AutomatedBuilds
  # pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Windows, macOS]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: WizardBubble
          preset: ${{ matrix.platform }}
          debugMode: "true"
          projectDir: "./ggj2025"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}

      # - name: create release
      #   uses: ncipollo/release-action@v1.14.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     generateReleaseNotes: true
      #     tag: ${{ github.ref_name }}
      #     artifacts: ${{ steps.export.outputs.archive_directory }}/*